### ISSUE TITLE
Deprecation warning: Use grpc.loadPackageDefinition

### ISSUE THREAD

**Issue by LightningK0ala** [Matt-Jensen/lnrpc#16]
Getting a warning when using this library. Should probably update the proto loading at some point to fix the deprecation warning.

`
DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
`

**Comment by Matt-Jensen** [comment]
Proto is requested directly from [LND/lnrpc/rpc.proto](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto) so it should be up to date, unless you haven't installed this package in a while.

At any rate I'll checkout that warning and see what can be done.

**Comment by Matt-Jensen** [comment]
Replace [usage of grpc.load](https://github.com/Matt-Jensen/lnrpc/blob/master/lib/lnrpc.js#L133) with  [proto-loader](https://www.npmjs.com/package/@grpc/proto-loader) and determine if google annotations can now be loaded instead of removed.

**Comment by LightningK0ala** [comment]
I worked on this a bit here: https://github.com/LightningK0ala/lnrpc

A couple of things...
- napa can cause a corrupt cache, so I added a napa-config to package.json which will ignore the cache, hopefully preventing users from getting stuck like I did today. [More details](https://github.com/shama/napa/issues/83)
- Leaving the annotations seems to work fine now.
- Making RPC calls works.
- Setting up subscriptions **doesn't work** :( I tried with subscribeInvoices and I'm getting the following error:

```
(node:66139) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'add_index' of undefined
    at Type.InvoiceSubscription$fromObject [as fromObject] (eval at Codegen (/~/LightningK0ala/lnrpc/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:7:8)
    at Type.fromObject (/~/LightningK0ala/lnrpc/node_modules/protobufjs/src/type.js:538:25)
    at serialize (/~/LightningK0ala/lnrpc/node_modules/@grpc/proto-loader/build/src/index.js:55:27)
    at Object.final_requester.sendMessage (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client_interceptors.js:1023:21)
    at InterceptingCall._callNext (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client_interceptors.js:418:43)
    at InterceptingCall.sendMessage (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client_interceptors.js:460:8)
    at InterceptingCall._callNext (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client_interceptors.js:424:12)
    at InterceptingCall.sendMessage (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client_interceptors.js:460:8)
    at Proxy.Client.makeServerStreamRequest (/~/LightningK0ala/lnrpc/node_modules/grpc/src/client.js:631:21)
    at apply (/~/LightningK0ala/lnrpc/node_modules/lodash/lodash.js:476:27)
(node:66139) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:66139) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Matt-Jensen** [comment]
Thanks for looking into this!  I'm working on this as well and also running into breakage with the new grpc definition.

While it creates the grpc definition from `rpc.proto` successfully, actually making calls has had mixed results for me as well.  For example `initWallet` is throwing errors with previously valid arguments.  Responses from the new grpc definition are completely different as well (ie camel cased instead of snake).

In light of this, I'm going to leave this issue open until the proto-loader package produces a more consistent definition with our current implementation.  Addressing the grpc-node package's warning at this time will result in breaking user code, which can't happen.  I'll commit the code I have so far.

In regards to the napa caching issue, lets address that in a different issue.  I'm not sure I 100% understand the problem you're having, but let's connect on the LND slack and hash it out if you're able to.

**Comment by LightningK0ala** [comment]
Glad to help!

Agreed, I've also stuck to the existing implementation for now. The camel case issue you're having can be fixed if you pass in an option, see:

https://github.com/LightningK0ala/lnrpc/blob/3831481292c8ef8884b6ecb28205075b696dbd22/lib/lnrpc.js#L133

I'll ping you on slack!

**Comment by LightningK0ala** [comment]
What's your handle?
